# fly.toml app configuration file generated for mrrper on 2024-09-11T22:07:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mrrper'
primary_region = 'waw'

[build]

[http_service]
internal_port = 8080
force_https = true
min_machines_running = 1
max_machines_running = 1
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
